capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('', RedirectView.as_view(url='/company/', permanent=True)) #This makes the /company/ the default base route
]

company/urls.py
from . import views
from django.urls import path

app_name = "company"

urlpatterns = [
    path('', views.index, name='index'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('fetchItems', views.fetchItems, name='fetchItems'),
    path('products', views.products, name='products'),
    path('products/<int:id>', views.productDetail, name='productDetail'),
    path('products/productPrice', views.productPrice, name='productPrice'),
    #path('fetchSuppliers', views.fetchSuppliers, name='fetchSuppliers'),
    path('suppliers', views.suppliers, name='suppliers'),
    path('supplierform', views.supplierForm, name='supplierForm'),
    path('suppliers/<int:id>', views.supplierDetail, name='supplierDetail'),
    path('personnel', views.personnel, name="personnel"),
    path('clients', views.clients, name='clients'),
    path('clientform', views.clientForm, name='clientForm'),
    path('clients/<int:id>', views.clientDetail, name='clientDetail'),
    path('jobs', views.jobs, name='jobs'),
    path('jobs/<int:id>', views.jobDetail, name='jobDetail'),
    path('supplies/<int:id>', views.supplies, name='supplies'),
    path('jobs/<str:type>/<int:id>', views.getItems, name='getItems'),
]

company/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from polymorphic.models import PolymorphicModel



# Create your models here.
class User(AbstractUser):
    pass


class Company(PolymorphicModel):
    id = models.BigAutoField(primary_key=True)
    nameC = models.CharField(max_length=64)
    address = models.IntegerField()
    email = models.CharField(max_length=64, default=0)
    contact = models.IntegerField()

    def __str__(self):
        return f"{self.nameC}"

class Supplier(Company):
    zone = models.IntegerField()
    location = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.nameC}"


class Client(Company):
    county = models.IntegerField()
    location = models.CharField(max_length=64)
    

    def __str__(self):
        return f"{self.nameC}"

class Product(models.Model):
    id = models.BigAutoField(primary_key=True)
    category = models.IntegerField()
    nameP = models.CharField(max_length=64)
    brand = models.CharField(max_length=64)
    size = models.IntegerField()
    weight = models.IntegerField()
    description = models.TextField()

    def __str__(self):
        productDetails = {
            "nameP":self.nameP, 
            "brand":self.brand,
            "category": self.category
            }
        #return str(productDetails)
        return f"{self.nameP}: {self.brand}"
        

class Price(models.Model):
    id = models.BigAutoField(primary_key=True)
    price = models.IntegerField()
    product = models.ForeignKey(Product, related_name="productPrice",on_delete=models.CASCADE, blank=True, null=True)
    supplier = models.ForeignKey(Supplier,related_name="products", on_delete=models.CASCADE, blank=True, null=True)
    #supplier = models.IntegerField()

    def __str__(self):
        return f"{self.price}"  
 

class Personnel(models.Model):
    id = models.BigAutoField(primary_key=True)
    nameC = models.CharField(max_length=64)
    contact = models.IntegerField()
    email = models.CharField(max_length=64)
    company = models.ForeignKey(Company, related_name="personnel", blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nameC}: {self.contact}"

class Job(models.Model):
    id = models.BigAutoField(primary_key=True)
    code = models.CharField(max_length=64)
    client = models.ForeignKey(Client, related_name="client", blank=True, on_delete=models.CASCADE)
    #product = models.ManyToManyField(Product, blank=True, related_name="jobProducts")
    value = models.IntegerField(null=True)
    status = models.CharField(max_length=64, default = "RFQ")
    lpo = models.CharField(max_length=64, blank=True)
    cheque = models.CharField(max_length=64, blank=True)

    def __str__(self):
        return f"{self.code}"

class Notes(models.Model):
    id = models.BigAutoField(primary_key=True)
    job = models.ForeignKey(Job, related_name="linkedJob", blank=True, on_delete=models.CASCADE)
    deliveryNo = models.CharField(max_length=64, blank=True)
    invoiceNo = models.CharField(max_length=64, blank=True)
    receiptNo = models.CharField(max_length=64, blank=True) 

    def __str__(self):
        return f"{self.id}: {self.job}: {self.deliveryNo}: {self.invoiceNo} "
    
class Supply(models.Model):
    id = models.BigAutoField(primary_key=True)
    qty = models.IntegerField()
    price = models.IntegerField()
    minBuying =  models.ForeignKey(Price, related_name="bestBuying", on_delete=models.CASCADE, blank=True, null=True)
    maxBuying =  models.ForeignKey(Price, related_name="worstBuying",on_delete=models.CASCADE, blank=True, null=True)
    total = models.IntegerField() 
    product = models.ForeignKey(Product, related_name="jobProduct",on_delete=models.CASCADE, blank=True, null=True)
    job = models.ForeignKey(Job, related_name="jobItem",on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.id}: {self.job}: {self.product}" 

       

company/views.py
from django.shortcuts import render
from . import templates, static, util
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, FileResponse
from django.shortcuts import redirect
from .models import *
import json, csv, io, xlsxwriter, math, os
from django.db.models import Avg, Max, Min, Sum, Subquery, OuterRef, FloatField, CharField, IntegerField
from itertools import chain
from django.db.models.functions import Cast
import pandas as pd
from django.core.mail import send_mail, EmailMultiAlternatives, EmailMessage
from capstone.settings import EMAIL_HOST_USER
from django.contrib import messages
from datetime import date, datetime
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template, render_to_string
from django.core.files.storage import FileSystemStorage

#Common variables
counties = util.get_data()["Counties"]
categories = util.get_data()["Categories"]
status = util.get_data()["Status"]
zones = util.get_data()["Zones"]
counties_dict = util.get_county()



# Create your views here.

def index(request):
    return render(request, "company/home.html")

def login_view(request):
    
    if request.method == "POST":
        n = request.POST.get('next', '')
        if n.rsplit('/', 1)[-1] == "login":
            n = reverse("company:index")
            
        #Authonticate the reseceived information
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(n) 
        else:
            return render(request, "company/login.html", {
                "message": "Invalid username and/or password."
            })

    return render(request, "company/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("company:login"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "company/register.html", {
                "message": "Passwords Don't match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "company/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("company:index"))

    return render(request, "company/register.html")

def products(request):
    products = Price.objects.all()
    suppliers = Supplier.objects.all()

    if request.method == "POST":
        #Collecting and Sorting Data
        rawdata = json.loads(request.body)
        newProduct = rawdata.get("newProduct")
        
        supplierId = int(newProduct.pop("supplier", None))
        price = int(newProduct.pop("productPrice", None))

        #Creating New Product
        new_product = Product(**newProduct)
        new_product.save()

        #Creating A price object
        supplier = suppliers.get(pk=supplierId)
        price = Price(price = price, product = new_product , supplier=supplier)
        price.save()

        response_data = {
            "message": "Product Stored Successfully.",
            "id": new_product.id
        }
        return JsonResponse(response_data, status=201)
    
    return render(request, "company/products.html",{
        #To display the products in reverse order, to place the recently added product on top
        "products": products[::-1],
        "suppliers": suppliers,
        "categories": categories
    })

def fetchItems(request):
    products = list(Product.objects.all().values())
    suppliers = list(Supplier.objects.all().values())
    jobs = list(Job.objects.all().values())
    prices = list(Price.objects.all().values())
    counties = json.dumps(counties_dict)
    data = json.dumps(util.get_data())

    response_data = {
        "products": products,
        "suppliers": suppliers,
        "jobs": jobs,
        "prices": prices,
        "counties": counties,
        "data": data
    }

    return JsonResponse(response_data, status=201)

def productDetail(request,id):
    products = Product.objects.all()
    if products.filter(pk=id).exists():
        product = Product.objects.get(pk=id)
        prices = product.productPrice.all()
        suppliers = Supplier.objects.all()
        
        if request.method == "GET":
            return render(request, "company/productdetails.html",{
                "product": product,
                "prices":prices,
                "suppliers": suppliers,
                "categories": categories
            })

        elif request.method == "PUT":
            data = json.loads(request.body)
            editedProduct = data.get("editedProduct")
            product.nameP = editedProduct["nameP"]
            product.brand = editedProduct["brand"]
            product.category = editedProduct["category"]
            product.weight = editedProduct["weight"]
            product.size = editedProduct["size"]
            product.description = editedProduct["description"]
            product.save()

            response_data = {
                "message": "Product Edited Successfully.",
                "id": product.id
            }
            return JsonResponse(response_data, status=201)

        else:
            id = json.loads(request.body)
            Product.objects.get(pk=id).delete()
            
            response_data = {
                "message": "Product Deleted."
            }
            return JsonResponse(response_data, status=201)
    else:
        return HttpResponse("Product Does Not exist")

def productPrice(request):
    if request.method == "POST":
        data = json.loads(request.body)
        newPrice = data.get("newPrice")
        product = Product.objects.get(pk=newPrice["product"])
        supplier = Supplier.objects.get(pk=newPrice["supplier"])
        price = Price(price = newPrice["price"], product = product , supplier=supplier)
        price.save()

        #Updating the corresponding supply items if any
        util.updateSupplies(price)
        

        response_data = {
            "message": "Price Added.",
            "id": price.id
        }
        return JsonResponse(response_data, status=201)
    elif request.method == "PUT":
        #Getting updated price
        data = json.loads(request.body)
        editPrice = int(data.get("editPrice"))
        priceId = int(data.get("priceId"))
        
        #Updating the price with the new value
        price = Price.objects.get(pk=priceId)
        price.price = editPrice
        price.save()

        #Updating the corresponding supply items if any
        util.updateSupplies(price)

        response_data = {
            "message": "Price Edited."
        }
        return JsonResponse(response_data, status=201)

    else:
        #Getting data from json
        data = json.loads(request.body)
        priceId = int(data.get("priceId"))
        
        #Getting the price to delete
        price = Price.objects.get(pk=priceId)
        product = price.product
        prices = product.productPrice.all()
        if prices.count()  > 1:
            #Updating the corresponding supply items if any
            util.updateSupplies(price)
            #Deleting the price
            price.delete()

            response_data = {
                "message": 1
            }
            return JsonResponse(response_data, status=201)
        else:
            response_data = {
                "message": 0
            }
            return JsonResponse(response_data, status=201)

def suppliers(request):
    suppliers = Supplier.objects.all()
    suppliers = suppliers.order_by("-id").all()

    #Paginating the suppliers
    paginator = Paginator(suppliers, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "company/suppliers.html",{
        # "suppliers" : suppliers
        "suppliers" : page_obj
    })

def supplierForm(request):
    if request.method == "POST":
        data = json.loads(request.body)
        newSupplier = data.get("newCompany")
        newSupplier.pop("county")
        new_supplier = Supplier(**newSupplier)
        new_supplier.save()
        
        response_data = {
            "message": "Supplier Added.",
            "id": new_supplier.id
        }
        return JsonResponse(response_data, status=201)
    else:
        return render(request, "company/companyForm.html", {
            "mode": "Supplier",
        })

def supplierDetail(request, id):
    supplier = Supplier.objects.get(pk=id)
    personnel = supplier.personnel.all() 
    products = Price.objects.filter(supplier=supplier)

    if request.method == "PUT":
        data = json.loads(request.body)
        ES = data.get("updateCompany")

        supplier.nameC = ES["nameC"]
        supplier.address = ES["address"]
        supplier.email = ES["email"]
        supplier.contact = ES["contact"]
        supplier.zone = ES["zone"]
        supplier.location = ES["location"]
        supplier.save()

        response_data = {
            "message": "Supplier Edited."
        }
        return JsonResponse(response_data, status=201)

    elif request.method == "DELETE":
        supplier.delete()

        response_data = {
            "message": "Supplier Deleted."
                
        }

company/templates/company/clients.html
{% extends "company/layout.html"%}

{% block body %}

<div class="container">
    <div class="d-flex justify-content-between mr-2">
        <h1>Clients</h1>
        
        <h4 class="align-self-center" >
          <a href="{% url 'company:clientForm' %}">+ Client </a> 
        </h4>
    </div>
        
    <div class="rounded mt-2 pt-2">
      <table class="table table-striped table-hover table-bordered border-primary pt-2">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Client</th>
              <th scope="col">Contact</th>
              <th scope="col">Location</th>
            </tr>
          </thead>
          <tbody id="companyTable">
              {%for client in clients %}
              <tr id="{{client.id}}" class="client">
                  <td scope="row" class="rowCounter"></td>
                  <td>{{client.nameC}}</td>
                  <td>{{client.contact}}</td>
                  <td>{{client.location}}</td>
              </tr>
              {%endfor%}
          </tbody>
        </table>
    </div>    
</div>

<div class="footer">
  {%with name1=clients name2="Clients" %}
    {% include "company/paginator.html" %}
  {%endwith%}
</div> 
{%endblock%}

{% load static %}
{% block scripttag%}
<script src="{% static 'company/company.js' %}"></script>
{%endblock%}

company/templates/company/index.html
{% extends "company/layout.html"%}

{% block body %}
<h1>Hello Company</h1>
{%endblock%}

company/templates/company/jobDetails.html
{% extends "company/layout.html"%}

{% block body %}
<div class="container">
    <div class="d-flex justify-content-between border-bottom mt-4 pb-3">
        <div id="name">
            <h2>
                <span  class="jDetail">{{job.code}}</span>
                <input id="code" class="inputUpdate form-control form-control-lg" style="display: none;" type="text" value="{{product.nameP}}">
                <span class="jobId" hidden>{{job.id}}</span>
                <span class="jobCounty" hidden>{{job.client.county}}</span>
            </h2>
        </div>
        <div class="d-flex align-items-center justify-content-between">
            <!-- <button class="btn btn-outline-primary btn-sm mx-2" id="editProduct">Edit Job</button> -->
            <button class="btn btn-outline-danger btn-sm" id="deleteJob">Delete</button>
        </div>
    </div>

    <div id="productDetails" class="row mt-3 border-bottom">
        <div class="border-bottom col-12 row pb-2">
            <div class="col-md-4">
                <h5>
                    Client:  
                    <span class="text-info jDetail">{{job.client}}</span>
                    
                </h5>
                <h5>
                    Value: 
                    {%if job.value%} 
                        <span class="text-info jDetail jValue">{{job.value}}</span>
                    {%else%}
                        <span class="text-info jDetail jValue">0</span>
                    {%endif%}
                </h5>
            </div>
            <div class="col-md-5">
                <h2 class="form-group row">
                    <!-- Status:  -->
                    <label for="status" class="col col-form-label">Status</label>
                    <div class="col row align-items-center">
                        <select id="status" class="inputUpdate form-control">
                            {% for status in status %}
                                {%if job.status == status %}
                                    <option value="{{job.status}}" selected>{{status}}</option>
                                {%else%}
                                    <option value="{{status}}">{{status}}</option>
                                {%endif%}    
                            {%endfor%}
                          </select>
                    </div>
                    <div class="col"></div>
                </h2>
            </div> 
            <div class="col-md-3 row print">
                <a  href="{% url 'company:getItems' 'print_rfq_csv' job.id %}">Check Analysis(CSV)</a>
                <a  href="{% url 'company:getItems' 'check_analysis' job.id %}">Check Analysis(Excel)</a>
                <div class="status_type row">
                    <a class="RFQ" href="{% url 'company:getItems' 'invoice_request' job.id %}">Request Invoice</a>
                    <a class="RFQ" href="{% url 'company:getItems' 'print_rfq_pdf' job.id %}">Print RFQ(pdf)</a>
                    <a class="LPO" href="{% url 'company:getItems' 'print_DI' job.id %}" >Print Delivery & Invoice</a>
                    <a class="Paid" href="{% url 'company:getItems' 'print_receipt' job.id %}">Print Receipt</a>
                </div>
            </div>
        </div>

        <!-- To display messages from backend -->

        <!-- {% if messages %}
            {% for message in messages %}
            <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %} -->

        <!-- Displaying the messages in bootstrap -->
            <!-- {% if messages %}
                {% for message in messages %}
                    <div class="container-fluid p-0">
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="True">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                    </div>
                {% endfor %}
            {% endif %} -->

    </div>

    <div class="card mt-3" id="productsSection">
        <div class="card-header d-flex justify-content-between">
            <h5>Job Products</h5>
        </div>
        
        <div class="input_status_change">

            <!-- Product input field -->
            <div class="RFQ">
                <div class="mt-2 mx-2">
                    <p class="text-info">Click Searched Item to Place the Item into the Product List</p> 
                </div>
                <div class="d-flex justify-content-between  m-2">
                    <div class="col-sm-6">
                        <input class="filterInput col-12 form-control" type="text" placeholder="Search Product">
                        <ul class="list-group list-group-flush" id="searchList"></ul>
                    </div>
                </div>
            </div>
        

            <!-- Feedding the LPO # and displaying the LPO in the LPO status -->
            <div class="LPO">
                <div class="LPO_body">
                {% if job.lpo %}
                    <div class="LPO_section">

                        <div class="mt-2 mx-2"> 
                            <h5 class="text-primary"> LPO No: {{job.lpo}}</h5>
                        </div>
                        
                        <div class="LPO">
                            <div class="mt-2 mx-2">
                                <a class="text-danger" >Click to change LPO No.</a>
                            </div>
                        </div>

                    </div>
                {%else%}
                    <div class="LPO_section">
                        <div class="mt-2 mx-2">
                            <p class="text-info">Feed in the LPO No. Below</p> 
                        </div>
                        <div class="d-flex justify-content-between  m-2">
                            <div class="col-sm-6">
                                <form id="LPO_iput" action="">
                                    <input id="" class=" LPO_iput col-12 form-control" type="text" placeholder="LPO No." required>
                                    <input type="submit" value="" hidden>
                                </form>
                            </div>
                        </div>
                    </div>
                {%endif%}
                </div>
            </div>

            <!-- Displaying the LPO and Cheque no in the respective modes -->
            {%if job.lpo %}
                <div class="RFQ Supplied Paid mt-2 mx-2"> 
                    <h5 class="text-primary"> LPO No: {{job.lpo}}</h5>
                </div>

                {%if job.cheque %}
                    <div class="RFQ LPO Paid mt-2 mx-2"> 
                        <h5 class="text-primary"> Cheque No: {{job.cheque}}</h5>
                    </div>
                {%endif%}
            {%endif%}

            <!-- Feeding in the cheque No -->
            <div class="Supplied">
                <div class="Supply_body">
                {% if job.cheque %}
                    <div class="supplied_section">

                        <div class="mt-2 mx-2"> 
                            <h5 class="text-primary"> Cheque No: {{job.cheque}}</h5>
                        </div>
                       
                        <div class="Supplied">
                            <div class="mt-2 mx-2">
                                <a class="text-danger" >Click to change Cheque No.</a>
                            </div>
                        </div>

                    </div>
                {%else%}
                    <div classs="supplied_section">
                        <div class="mt-2 mx-2">
                            <p class="text-info">Feed in the Cheque No. Below</p> 
                        </div>
                        <div class="d-flex justify-content-between  m-2">
                            <div class="col-sm-6">
                                <form id="s_iput" action="">
                                    <input id="" class=" s_iput col-12 form-control" type="text" placeholder="Cheque No." required>
                                    <input type="submit" value="" hidden>
                                </form>
                            </div>
                        </div>
                    </div>
                {%endif%}
                </div>
            </div>

        </div>

        <div class="table-responsive my-4" id="products">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th scope="col" style="width:3%" class="text-center">#</th>
                    <th scope="col" style="width:20%" class="text-center">Name</th>
                    <th scope="col" style="width:18%" class="text-center">Category</th>
                    <th scope="col" style="width:18%" class="text-center">QTY</th>
                    <th scope="col" style="width:18%" class="text-center">Price</th>
                    <th scope="col" style="width:18%" class="text-center">Total</th>
                    <th class="status_hide" scope="col" class="text-center">Action</th>
                  </tr>
                </thead>
                <tbody id="suppliesTable">
                    {% for supply in supplies %}
                        <tr id="{{supply.id}}" class="{{supply.product.id}}">
                            <th scope="row" class="rowCounter text-center"></th>
                            <td id="name" class="text-center" >{{supply.product.nameP}} : {{supply.product.brand}} </td>
                            <td id="category" class="text-center">{{supply.product.category}}</td>
                            <td id="qty" class="text-center">{{supply.qty}}</td>
                            <td id="price" class="price text-center">{{supply.price}}</td>
                            <td id="total" class="text-center">{{supply.total}}</td>
                            <td class="status_hide">
                                <div class="d-flex justify-content-center">
                                    <button id="editButton" class="pr-1 btn btn-lg text-dark" >
                                        <i class="far fa-edit"></i>
                                    </button>
                                    <button id="deleteButton" class="pl-0 btn btn-lg text-dark">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr id="hiddenRow" style="display: none;">
                        <th scope="row" class="rowCounter text-center"></th>
                        <td class="text-center">
                            <input type="text" class="productName form-control filterInput">
                            <ul class="list-group list-group-flush" id="searchList"></ul>
                        </td>
                        <td class="text-center"><input type="text" class="category form-control" disabled></td>
                        <td id="qty" class="text-center"><input type="text" class="qty form-control" disabled></td>
                        <td id="price" class="text-center"><input type="text" class="price form-control" disabled></td>
                        <td id="total" class="text-center"><input type="text" class="total form-control" disabled></td>
                        <td class="d-flex justify-content-center">
                            <button id="saveProduct" class="pr-1 btn btn-lg text-dark" >
                                <i class="fa fa-check"></i>
                            </button>
                            <button id="cancelButton" class="pl-0 btn btn-lg text-dark">
                                <i class="fa fa-ban"></i>
                            </button>
                        </td>    
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="d-flex flex-row-reverse m-2">
            <button class="btn btn-primary" id="addProduct">Add Product</button>
        </div>

    </div>

{% if messages %}
{% for message in messages %}
    <script>
        alert('{{ message }}');
    </script>
{% endfor %}
{% endif %}  

{%endblock%}

{% load static %}

{% block scripttag%}
<script src="{% static 'company/jobDetails.js' %}"></script>
{%endblock%}

company/templates/company/suppliers.html
{% extends "company/layout.html"%}

{% block body %}

<div class="container">
    <div class="d-flex justify-content-between mr-2">
        <h1>Suppliers</h1>
        
        <h4 class="align-self-center" >
          <a href="{% url 'company:supplierForm' %}">+ Supplier </a> 
        </h4>
    </div>
        
    <div class="rounded mt-2 pt-2">
      <table class="table table-striped table-hover table-bordered border-primary pt-2">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Supplier</th>
              <th scope="col">Contact</th>
              <th scope="col">Location</th>
            </tr>
          </thead>
          <tbody id="companyTable">
              {%for supplier in suppliers %}
              <tr id="{{supplier.id}}" class="suppliers">
                  <td scope="row" class="rowCounter"></td>
                  <td>{{supplier.nameC}}</td>
                  <td>{{supplier.contact}}</td>
                  <td>{{supplier.location}}</td>
              </tr>
              {%endfor%}
          </tbody>
        </table>
    </div>  
    
</div>
<div class="footer">
  {%with name1=suppliers name2="Suppliers" %}
    {% include "company/paginator.html" %}
  {%endwith%}
</div> 
{%endblock%}

{% load static %}
{% block scripttag%}
<script src="{% static 'company/company.js' %}"></script>
{%endblock%}